# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1053, 694)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messageWidget = QtWidgets.QListWidget(self.centralwidget)
        self.messageWidget.setGeometry(QtCore.QRect(0, 0, 801, 441))
        self.messageWidget.setObjectName("messageWidget")
        self.typeBox = QtWidgets.QComboBox(self.centralwidget)
        self.typeBox.setGeometry(QtCore.QRect(0, 440, 121, 22))
        self.typeBox.setObjectName("typeBox")
        self.typeBox.addItem("")
        self.typeBox.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 460, 801, 211))
        self.textEdit.setObjectName("textEdit")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(720, 630, 81, 41))
        self.sendButton.setObjectName("sendButton")
        self.MemberView = QtWidgets.QListView(self.centralwidget)
        self.MemberView.setGeometry(QtCore.QRect(800, 30, 251, 641))
        self.MemberView.setObjectName("MemberView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(810, 10, 54, 12))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1053, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionsignout = QtWidgets.QAction(MainWindow)
        self.actionsignout.setObjectName("actionsignout")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menu.addAction(self.actionsignout)
        self.menu.addAction(self.actionexit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "聊天吧！"))
        self.typeBox.setItemText(0, _translate("MainWindow", "发送文字"))
        self.typeBox.setItemText(1, _translate("MainWindow", "发送指令"))
        self.sendButton.setText(_translate("MainWindow", "发送"))
        self.label.setText(_translate("MainWindow", "人员列表"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actionsignout.setText(_translate("MainWindow", "signout"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
